spring.application.name=wineapp

# URL de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/wineapp
# Credenciales de la base de datos
spring.datasource.username=postgres
spring.datasource.password=admin

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
# 'update' creará las tablas automaticamente basándose en las clases Java, pero no eliminará tablas ni datos existentes
spring.jpa.hibernate.ddl-auto=update
# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
# Formatear las consultas SQL para mejor legibilidad
spring.jpa.properties.hibernate.format_sql=true

#Silenciar el aviso "Open-in-view"
spring.jpa.open-in-view=false